version = 1
SPDX-PackageName = "ironcore-csi-driver"
SPDX-PackageSupplier = "IronCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/ironcore-dev/ironcore-csi-driver"

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    ".golangci.yaml",
    "CODEOWNERS",
    "CODE_OF_CONDUCT.md",
    "Dockerfile",
    "Makefile",
    "PROJECT",
    "config/**",
    "go.mod",
    "go.sum",
    "hack/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["docs/**", "README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"
