apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: ironcore-csi-creds
metadata:
  name: ironcore-csi-driver
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ironcore-csi-driver
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["watch", "list", "get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update", "create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete", "get", "update"]
  - apiGroups: ["storage.ironcore.dev"]
    resources: ["volumeclaims"]
    verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
  - apiGroups: ["compute.ironcore.dev"]
    resources: ["machines"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.ironcore.dev"]
    resources: ["volumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ironcore-csi-driver
subjects:
  - kind: ServiceAccount
    name: ironcore-csi-driver
    namespace: default
roleRef:
  kind: ClusterRole
  name: ironcore-csi-driver
  apiGroup: rbac.authorization.k8s.io
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: ironcore-csi-driver
  namespace: default
spec:
  selector:
    matchLabels:
      app: ironcore-csi-driver
  serviceName: ironcore-csi-driver
  replicas: 1
  template:
    metadata:
      labels:
        app: ironcore-csi-driver
    spec:
      serviceAccountName: ironcore-csi-driver
      containers:
        - name: attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.9.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true 
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              memory: 210Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "--volume-name-prefix=csi-ironcore"
            - "--volume-name-uuid-length=10"
            - "--feature-gates=Topology=true"
            - "--timeout=300s"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          resources:
            requests:
              cpu: 11m
              memory: 32Mi
            limits:
              memory: 200Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-snapshotter
          image: registry.k8s.io/sig-storage/csi-snapshotter:v8.3.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.14.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 200Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true  
          image: ironcore-csi-driver:latest
          imagePullPolicy: IfNotPresent
          args:
          - "--target-kubeconfig=/etc/csi.ironcore.dev/target-kubeconfig"
          - "--ironcore-kubeconfig=/etc/csi.ironcore.dev/ironcore-kubeconfig"
          env:
            - name: CSI_ENDPOINT
              value: /csi/csi.sock
            - name: APP_LOG_LEVEL
              value: "info"
            - name: X_CSI_MODE
              value: controller
            - name: X_CSI_SPEC_DISABLE_LEN_CHECK
              value: "true"
            - name: X_CSI_DEBUG
              value: "false"
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VOLUME_NS
              valueFrom:
                secretKeyRef:
                  name: ironcore-csi
                  key: namespace
          resources:
            requests:
              cpu: 20m
              memory: 50Mi
            limits:
              memory: 210Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: kubeconfig-volume
              mountPath: /etc/csi.ironcore.dev
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 3
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.16.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=4"
            - "--csi-address=/csi/csi.sock"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 110Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: kubeconfig-volume
          secret:
            secretName: ironcore-csi
