apiVersion: v1
kind: ServiceAccount
metadata:
  name: ironcore-csi-node
  namespace: default
imagePullSecrets:
- name: ironcore-csi-creds
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ironcore-csi-node
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumesclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ironcore-csi-node
subjects:
  - kind: ServiceAccount
    name: ironcore-csi-node
    namespace: default
roleRef:
  kind: ClusterRole
  name: ironcore-csi-node
  apiGroup: rbac.authorization.k8s.io
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ironcore-csi-node
  namespace: default
spec:
  selector:
    matchLabels:
      app: ironcore-csi-node
  template:
    metadata:
      labels:
        app: ironcore-csi-node
    spec:
      serviceAccountName: ironcore-csi-node
      hostNetwork: true
      containers:
        - name: registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.14.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.ironcore.dev/csi.sock
          securityContext:
            privileged: true
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 11m
              memory: 32Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - name: registration-dir
              mountPath: /registration
            - name: socket-dir
              mountPath: /csi
        - name: driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true              
          image: ironcore-csi-driver:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: X_CSI_MODE
              value: node
            - name: X_CSI_DEBUG
              value: "false"
            - name: APP_LOG_LEVEL
              value: "info"
            - name: X_CSI_SPEC_DISABLE_LEN_CHECK
              value: "true"
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 15m
              memory: 42Mi
            limits:
              memory: 2Gi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: pods-probe-dir
              mountPath: /dev
              mountPropagation: HostToContainer
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 5
            failureThreshold: 3
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.16.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=4"
            - "--csi-address=/csi/csi.sock"
          resources:
            requests:
              cpu: 11m
              memory: 32Mi
            limits:
              memory: 200Mi
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: pods-probe-dir
          hostPath:
            path: /dev
            type: Directory
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.ironcore.dev
            type: DirectoryOrCreate
