apiVersion: v1
kind: ServiceAccount
metadata:
  name: onmetal-csi-node
  namespace: default
imagePullSecrets:
- name: onmetal-csi-creds
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onmetal-csi-node
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "delete", "get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumesclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onmetal-csi-node
subjects:
  - kind: ServiceAccount
    name: onmetal-csi-node
    namespace: default
roleRef:
  kind: ClusterRole
  name: onmetal-csi-node
  apiGroup: rbac.authorization.k8s.io
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: onmetal-csi-node
  namespace: default
spec:
  selector:
    matchLabels:
      app: onmetal-csi-node
  template:
    metadata:
      labels:
        app: onmetal-csi-node
    spec:
      serviceAccountName: onmetal-csi-node
      hostNetwork: true
      containers:
        - name: registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v2.5.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi.onmetal.de/csi.sock
          securityContext:
            privileged: true
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: registration-dir
              mountPath: /registration
            - name: driver-path
              mountPath: /csi
        - name: driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true              
          image: onmetal-csi-driver:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CSI_ENDPOINT
              value: unix://csi/csi.sock
            - name: X_CSI_MODE
              value: node
            - name: X_CSI_DEBUG
              value: "false"
            - name: APP_LOG_LEVEL
              value: "info"
            - name: CSI_DRIVER_NAME
              value: "onmetal-csi-driver"
            - name: X_CSI_SPEC_DISABLE_LEN_CHECK
              value: "true"
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
            - name: pods-probe-dir
              mountPath: /dev
              mountPropagation: HostToContainer
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: pods-probe-dir
          hostPath:
            path: /dev
            type: Directory
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.onmetal.de
            type: DirectoryOrCreate