apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
  namespace: ironcore-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ironcore-storageclass-demo
