apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-demo
spec:
  volumeSnapshotClassName: ironcore-storageclass-demo # must be same as storageClassName as Ironcore does not have a seperate volumeSnapshot class
  source:
    persistentVolumeClaimName: pvc-demo
