apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ironcore-storageclass-demo
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  type: "volume_class"
allowVolumeExpansion: true
provisioner: csi.ironcore.dev
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
