apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
  namespace: onmetal-csi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: onmetal-storageclass-demo