apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: onmetal-storageclass-demo
provisioner: onmetal-csi-driver
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  fstype: ext4
  storage_pool: "fra3"
  storage_class_name: "slow"