apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
- name: onmetal-csi-creds
metadata:
  name: onmetal-csi-driver
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onmetal-csi-driver
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodeinfos"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["watch", "list", "get"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents/status"]
    verbs: ["update", "create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots/status"]
    verbs: ["get", "list", "watch", "update", "create", "delete", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "list", "watch", "delete", "get", "update"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: onmetal-csi-driver
subjects:
  - kind: ServiceAccount
    name: onmetal-csi-driver
    namespace: default
roleRef:
  kind: ClusterRole
  name: onmetal-csi-driver
  apiGroup: rbac.authorization.k8s.io
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: onmetal-csi-driver
  namespace: default
spec:
  selector:
    matchLabels:
      app: onmetal-csi-driver
  serviceName: onmetal-csi-driver
  replicas: 1
  template:
    metadata:
      labels:
        app: onmetal-csi-driver
    spec:
      serviceAccount: onmetal-csi-driver
      containers:
        - name: attacher
          image: quay.io/k8scsi/csi-attacher:v2.0.0
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true 
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.4.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--volume-name-prefix=csi-onmetal"
            - "--volume-name-uuid-length=10"
            - "--connection-timeout=300s"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: snapshotter
          image: quay.io/k8scsi/csi-snapshotter:v1.2.2
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"   
            - "--snapshot-name-prefix=onmetalsnap"
            - "--snapshot-name-uuid-length=10"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
        - name: resizer
          image: quay.io/k8scsi/csi-resizer:v0.3.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/run/csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi      
        - name: driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true  
          image: onmetal-csi-driver:latest
          imagePullPolicy: Always
          env:
            - name: CSI_ENDPOINT
              value: /var/run/csi/csi.sock
            - name: PARENT_KUBE_CONFIG
              value: "/etc/parent-kubeconfig/kubeconfig.yaml"
            - name: APP_LOG_LEVEL
              value: "info"
            - name: CSI_DRIVER_NAME
              value: "onmetal-csi-driver"
            - name: CSI_DRIVER_VERSION
              value: "1.0.0"
            - name: X_CSI_MODE
              value: controller
            - name: X_CSI_DEBUG
              value: "false"
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /var/run/csi
            - name: kubeconfig-volume
              mountPath: /etc/parent-kubeconfig    
      volumes:
        - name: socket-dir
          emptyDir:
        - name: kubeconfig-volume
          secret:
            secretName: kubeconfig-secret    
