name: Check

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: go mod tidy
      - run: hack/check.sh
