name: Lint Golang Codebase

on:
  pull_request_target:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: actions/checkout@v3
      - run: ./hack/setup-git-redirect.sh
        env:
          GITHUB_PAT: ${{ secrets.BOT_PAT }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.43.0
