name: Pull Request Code test

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  checks:
    name: run
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      # run a test cluster to get the in-cluster config for make test
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - run: make test
